version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./webroot/:/var/www/html/
      - ./logs/:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    networks:
      - internal
    volumes:
      - ./webroot/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    image: mysql:5.7.43
    networks:
      - internal
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
      TZ: Asia/Shanghai
    ports:
      - "127.0.0.1:3306:3306"
networks:
  internal:
    driver: bridge